Header
IgorN1989/foodsta-19 pull request #14
Opened 2022-08-26 17:01 UTC by ArtemGR1987

2022-08-26 18:34 UTC, IgorN1989 requested changes

2022-08-26 18:34 UTC, IgorN1989 commented on src/partials/header.html
> +  <div class="header__container--container">
тут просто class="container"

Я говорив, що можливо унікалні будуть секції. Твого розділу це не стосується, у тебе не має тегу "section". У тебе аналог - "header"

2022-08-26 18:34 UTC, IgorN1989 commented on src/partials/header.html
> +      class="menu-button__icon"
class="menu-button"

2022-08-26 18:34 UTC, IgorN1989 commented on src/partials/header.html
> +      <svg width="28" height="28" aria-label="Mobile menu switch">
class="menu-button__icon"

2022-08-26 18:34 UTC, IgorN1989 commented on src/partials/header.html
> +    <!-- Мобильное меню -->
Це взагалі не потрібно. У тебе вже все це є в навігації. Можеш просто навігацію обгорнути в div і все

2022-08-27 09:56 UTC, ArtemGR1987 commented on src/partials/header.html
> +    <!-- Мобильное меню -->
Не понял.. Что не нужно?

2022-08-27 09:59 UTC, ArtemGR1987 commented
Подправил

2022-08-27 10:21 UTC, IgorN1989 requested changes

2022-08-27 10:21 UTC, IgorN1989 commented on src/partials/header.html
> +    <!-- Мобильное меню -->
все, що ти написав під коментарем  <!-- Мобильное меню --> строки 24-44. Ти просто продоблював навігацію. Так не потрібно робити. В тебе вже є це меню. Єдине, що ок, це залишити дів і вкласти в нього навігацію
`<div class="mobile-menu" id="mobile-menu" data-menu>`
`<!-- Меню навигации -->`
`</div>`

2022-08-27 10:21 UTC, IgorN1989 commented on src/partials/header.html
> +      <svg width="28" height="28" aria-label="Mobile menu switch">
svg class="menu-button__icon"

2022-08-27 11:33 UTC, IgorN1989 approved these changes

2022-08-27 11:33 UTC, IgorN1989 commented on src/partials/header.html
> +        <use href="#">logo</use>
ЛОГО вже є в спрайті

href="./images/icons/sprite.svg#logo"

2022-08-27 12:08 UTC, merged